# Generated by Django 5.0.4 on 2024-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(max_length=2)),
                ('score', models.IntegerField(max_length=2)),
            ],
        ),
    ]
