# Generated by Django 4.2.3 on 2024-04-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_marks1'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='session_id',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='marks1',
            name='session_id',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='marks1',
            name='gpa',
            field=models.FloatField(max_length=4),
        ),
    ]
